### ISSUE TITLE
生成图像的问题

### ISSUE THREAD

**Issue by lemongad** [LLM-Red-Team/qwen-free-api#1]
接入one-api.使用nextchat,
用户: "生成 小狗图像"
AI: 正在生成中
就没有图像
在官网，也是会提示正在生成中，但是比较慢还是会有图片生成。

**Comment by Vinlic** [comment]
@lemongad 图像生成还未处理，今天或者明天支持后会更新

**Comment by Vinlic** [comment]
@lemongad 0.0.2已支持AI绘图
<img width="496" alt="image" src="https://github.com/LLM-Red-Team/qwen-free-api/assets/20235341/9cee7d89-167c-4006-bbf8-154454e400e5">

**Comment by Vinlic** [comment]
@spacex-3 0.0.5版本已经支持/v1/images/generations接口
