### ISSUE TITLE
怎么上传本地文件呢？有没有大佬知道

### ISSUE THREAD

**Issue by 332123342** [LLM-Red-Team/qwen-free-api#10]
<img width="870" alt="image" src="https://github.com/LLM-Red-Team/qwen-free-api/assets/120700204/466dcaa9-8527-450e-ad69-088846ebabd1">
这里只能写url吗？

**Comment by 332123342** [comment]
目前的想到的办法是把本地文件先上传到github上，再去到url。。。

**Comment by 332123342** [comment]
> 请将文件编码为base64提供在url位置，base64前面还需要提供数据头，比如上传jpg文件需要这样提供： "url": "data:image/jpeg;base64,/9j/4AAQSkZJRgA..." @332123342

文件大小有几兆，这样有问题吗？

**Comment by Vinlic** [comment]
@332123342 没问题的，十几M的也传过

**Comment by 332123342** [comment]
```
response = client.chat.completions.create(
    model="qwen",
    messages = [
        {
            "role": "user",
            "content": [
                {
                    "type": "file",
                    "file_url": {
                        "url": "data:text/plain,aSBhbSBhIGdvb2QgYm95"
                    }
                },
                {
                    "type": "text",
                    "text": "上传的文档说了什么"
                }
            ]
        }
    ],
)
```
试了一下好像不行。。。
<img width="757" alt="image" src="https://github.com/LLM-Red-Team/qwen-free-api/assets/120700204/a1c51817-47fc-49aa-8faa-f147b0e42b56">
