### ISSUE TITLE
qwen和kimi分开端口部署能同时使用吗？

### ISSUE THREAD

**Issue by Bald0Wang** [LLM-Red-Team/qwen-free-api#12]
目前部署了kimi可以  但是qwen换8001，访问失败了

**Comment by Vinlic** [comment]
把端口错开启动
docker部署：参数指定-p 8001:8000
原生部署：pm2 start dist/index.js --name "qwen-free-api" -- --port 8001

**Comment by Bald0Wang** [comment]
搞定了  我改了server.yaml  = =忘记我的服务器没开8001……谢谢大佬  再次感谢！
