### ISSUE TITLE
vercel部署后出错

### ISSUE THREAD

**Issue by younggggger** [LLM-Red-Team/qwen-free-api#13]
服务部署后的链接
404: NOT_FOUND
Code: NOT_FOUND
ID: cle1::tc5cp-1713763543805-85c2ae99bdcc

**Comment by younggggger** [comment]
我在vercel里配置了环境变量Authorization: Bearer 我的login_tongyi_ticket     还是不正常

**Comment by Vinlic** [comment]
@younggggger 部署步骤可能错误，请在本地用vercel cli部署，需要注意，vercel部署的请求响应超时时间是10s

**Comment by younggggger** [comment]
> @younggggger 部署步骤可能错误，请在本地用vercel cli部署，需要注意，vercel部署的请求响应超时时间是10s

我就是本地 cli部署的，另外本地cli部署，Authorization的值需要修改哪个文件吗。

**Comment by younggggger** [comment]
![image](https://github.com/LLM-Red-Team/qwen-free-api/assets/127868785/5f6109e8-a291-40f6-bb3f-f284fd98f44c)

**Comment by younggggger** [comment]
@Vinlic 能看出啥问题吗
