### ISSUE TITLE
是不是方案失效了？

### ISSUE THREAD

**Issue by homeyone** [LLM-Red-Team/qwen-free-api#23]
{"code":"InvalidParameter","message":"Range of input length should be [1, 6000]","request_id":"xxxxxx-xxx-xxx-xxx-xxx"}
之前还是好好的，并且之前测试好像最大是60000不是6000

**Comment by Vinlic** [comment]
这个响应不是来自free-api，也不是千问的异常，请检查你用的中间框架。
