### ISSUE TITLE
没有找到login_tongyi_ticket

### ISSUE THREAD

**Issue by A-Nobel** [LLM-Red-Team/qwen-free-api#24]
未找到login_tongyi_ticket
![image](https://github.com/LLM-Red-Team/qwen-free-api/assets/49715687/eb1218c5-01e5-4c91-81df-0e7c14f60277)

**Comment by Vinlic** [comment]
如果你登录过阿里云账号需要先退出登录重登才会有，或者直接在0.0.17版本使用login_aliyunid_ticket也行。
