### ISSUE TITLE
接入应用异常

### ISSUE THREAD

**Issue by Magnoliar** [LLM-Red-Team/qwen-free-api#26]
项目用docker部署在阿里云，本地用示例代码跑了一下，可以正确响应
![image](https://github.com/LLM-Red-Team/qwen-free-api/assets/18226972/a7b65d64-a707-4b7a-9f57-2b812291e1cf)
但是在接入具体的应用的时候，不管是lobechat、nextchat还是oneapi，都无法正常返回，其中nextchat返回：
{
  "error": true,
  "message": "Failed to fetch"
}
lobechat返回为空
oneapi返回错误：json: cannot unmarshal number into Go struct field ChatResponse.code of type string

**Comment by Vinlic** [comment]
检查写的代理地址是否正确，以及ticket是否填写错误，可以结合free api日志排查
