### ISSUE TITLE
流式输出似乎不太正常

### ISSUE THREAD

**Issue by Feliks151450** [LLM-Red-Team/qwen-free-api#3]
要等很久才有输出，一输出就是一大段内容，然后又停住，等半天再输出一大段内容。
使用docker命令直接装的，没做什么调整。
也同样装了kimi-free和glm-free，这两个都正常，只有qwen-free流式不正常，应该不是我操作的问题吧，这也没什么可操作的空间了

**Comment by Vinlic** [comment]
@Feliks151450 qwen的流确实有别于其它两家，是一坨一坨的输出，且首token非常慢，除了他们缓存的结果会快之外，他们前端做了打字机效果处理所以才看上去比较流畅。

**Comment by Yanyutin753** [comment]
要不每秒加个sleep一下

**Comment by Yanyutin753** [comment]
或者队列缓冲一下哈哈哈哈哈

**Comment by Vinlic** [comment]
@Yanyutin753 在考虑缓冲区实现

**Comment by Yanyutin753** [comment]
@Vinlic 大佬强的哈哈哈哈

**Comment by Vinlic** [comment]
@spacex-3 明晚会搞这个

**Comment by spacex-3** [comment]
> @spacex-3 明晚会搞这个

收到，那就不等其他佬二开了，直接无缝套用你的项目就行，等大佬更新了！

**Comment by spacex-3** [comment]
> @spacex-3 明晚会搞这个

其他那几个项目有绘图的其实也可以搞搞的，用处就大很多啦

**Comment by Vinlic** [comment]
@spacex-3 是一起搞的

**Comment by spacex-3** [comment]
> @spacex-3 是一起搞的

many thanks!

**Comment by Vinlic** [comment]
@spacex-3 0.0.5版本已经支持/v1/images/generations接口

**Comment by Vinlic** [comment]
最新版本 0.0.9 已经优化，流响应首token耗时缩短，输出流畅度提升。 
[切换HTTP/2优化流响应速度](https://github.com/LLM-Red-Team/qwen-free-api/commit/c259afa34dca9b2354f34c28e0db649a47602a7c)
