### ISSUE TITLE
搭建完成，正常使用第二天之后被封号了

### ISSUE THREAD

**Issue by gz4zzxc** [LLM-Red-Team/qwen-free-api#32]
在使用了 [qwen-free-api](https://github.com/LLM-Red-Team/qwen-free-api) 项目之后，使用了等效 0.5 刀的 qwen-max，结果第二天账号就被冻结了 😭。放在这给后人警示。

**Comment by gz4zzxc** [comment]
![CleanShot 2024-05-20 at 13 10 24](https://github.com/LLM-Red-Team/qwen-free-api/assets/33158166/48001b10-ad3d-4568-921d-7d3bee5312bf)

**Comment by Vinlic** [comment]
频率过高或并发的非正常调用都有可能导致封禁，需谨慎使用。

**Comment by khailifz** [comment]
> 频率过高或并发的非正常调用都有可能导致封禁，需谨慎使用。

那我如果充值的话，如何用qwen-free-api调用我得付费api可以吗？  我主要觉得qwen网页版回复个消息太慢太慢了

**Comment by Vinlic** [comment]
那直接调用官方api接口就可以了，不需要经过free-api @khailifz
