### ISSUE TITLE
上下文多轮问答提交conversation_id，没有起作用

### ISSUE THREAD

**Issue by shyBoy-ico** [LLM-Red-Team/qwen-free-api#36]

**Comment by Vinlic** [comment]
提供你的传参检查

**Comment by shyBoy-ico** [comment]
async def qwen_ai_free(self, params, model='qwen-turbo', stream=False):
        headers = {
            'Authorization': f'Bearer {self.auth_token}',
            'Content-Type': 'application/json'
        }
        data = {
            'model': model,
            'conversation_id': params['convers_id'],
            'messages': [{
                'role': 'user',
                'content': params['question']
            }],
            'stream': stream
        }
        print(data)
        url = self.base_url+'/v1/chat/completions'
        response = requests.post(url, headers=headers, json=data)
        return response.json()

**Comment by Vinlic** [comment]
conversation_id打印一下

**Comment by shyBoy-ico** [comment]
`    async def qwen_ai_free(self, params, model='qwen-turbo', stream=False):
        headers = {
            'Authorization': f'Bearer {self.auth_token}',
            'Content-Type': 'application/json'
        }
        data = {
            'model': model,
            'conversation_id': params['convers_id'],
            'messages': [{
                'role': 'user',
                'content': params['question']
            }],
            'stream': stream
        }
        print(data)
        url = self.base_url+'/v1/chat/completions'
        response = requests.post(url, headers=headers, json=data)
        return response.json()`
      convers_id 就是前端提交的上一个返回的ID，  question是新的问题

**Comment by shyBoy-ico** [comment]
async def qwen_ai_free(self, params, model='qwen-turbo', stream=False):
        headers = {
            'Authorization': f'Bearer {self.auth_token}',
            'Content-Type': 'application/json'
        }
        data = {
            'model': model,
            'conversation_id': params['convers_id'],
            'messages': [{
                'role': 'user',
                'content': params['question']
            }],
            'stream': stream
        }
        print(data)
        url = self.base_url+'/v1/chat/completions'
        response = requests.post(url, headers=headers, json=data)
        return response.json()
        
{'model': 'qwen-turbo', 'conversation_id': 'fcbcc9f9dd86491ba0a2bd8aed0a9247', 'messages': [{'role': 'user', 'content': '他会和周树人打架嘛'}], 'stream': False}

**Comment by shyBoy-ico** [comment]
{
    "code": 200,
    "message": "success",
    "data": {
        "id": "84933f0b6f3041818dc0807625733f1e",
        "model": "qwen",
        "object": "chat.completion",
        "choices": [
            {
                "index": 0,
                "message": {
                    "role": "assistant",
                    "content": "您的问题似乎是在询问某人是否会与周树人（鲁迅）发生冲突或打架。需要明确的是，周树人，即鲁迅，是中国现代著名的文学家、思想家，他已经于1936年去世。因此，无论是从历史事实还是逻辑上讲，任何人都不可能与已故的鲁迅发生实际的身体冲突或打架。\n\n如果您的问题是比喻性的，想了解某人是否会在思想观念上与鲁迅有分歧或“斗争”，那么这取决于这个人持有的观点与鲁迅的思想、文学作品或是社会批评是否相左。鲁迅的作品中充满了对社会现象的深刻批判和独到见解，不同的人根据自己的价值观和理解，可能会有赞同或异议，这种意义上的“交锋”是思想文化的交流与碰撞，而非实际的肢体冲突。"
                },
                "finish_reason": "stop"
            }
        ],
        "usage": {
            "prompt_tokens": 1,
            "completion_tokens": 1,
            "total_tokens": 2
        },
        "created": 1717581507
    }
}

**Comment by shyBoy-ico** [comment]
{
    "code": 200,
    "message": "success",
    "data": {
        "id": "84933f0b6f3041818dc0807625733f1e",
        "model": "qwen",
        "object": "chat.completion",
        "choices": [
            {
                "index": 0,
                "message": {
                    "role": "assistant",
                    "content": "您的问题似乎是在询问某人是否会与周树人（鲁迅）发生冲突或打架。需要明确的是，周树人，即鲁迅，是中国现代著名的文学家、思想家，他已经于1936年去世。因此，无论是从历史事实还是逻辑上讲，任何人都不可能与已故的鲁迅发生实际的身体冲突或打架。\n\n如果您的问题是比喻性的，想了解某人是否会在思想观念上与鲁迅有分歧或“斗争”，那么这取决于这个人持有的观点与鲁迅的思想、文学作品或是社会批评是否相左。鲁迅的作品中充满了对社会现象的深刻批判和独到见解，不同的人根据自己的价值观和理解，可能会有赞同或异议，这种意义上的“交锋”是思想文化的交流与碰撞，而非实际的肢体冲突。"
                },
                "finish_reason": "stop"
            }
        ],
        "usage": {
            "prompt_tokens": 1,
            "completion_tokens": 1,
            "total_tokens": 2
        },
        "created": 1717581507
    }
}

**Comment by Vinlic** [comment]
你应该更新到最新版本了，最新版本的conversation_id是类似`bc9ef150d0e44794ab624df958292300-40811965812e4782bb87f1a9e4e2b2cd`

**Comment by shyBoy-ico** [comment]
就是我要更新我的版本是吧

**Comment by Vinlic** [comment]
是的
