### ISSUE TITLE
请求提交的token经常报错

### ISSUE THREAD

**Issue by shyBoy-ico** [LLM-Red-Team/qwen-free-api#37]
服务暂时不可用，第三方响应错误:NOT_LOGIN
[请求qwen失败]:NOT LOGIN-未登录
服务暂时不可用，第三方响应错 answer: SESSION NO EXIST"
请求有时报这个类似的错误，怎么解决呢

**Comment by Vinlic** [comment]
检查你传入的token是否有效，SESSION NO EXIST一般代表会话不存在，可能传入了错误的conversationId，如果你使用了原生多轮，需要确保conversationId是属于对应用户token的，因为一个用户无法访问另一个用户的会话。

**Comment by shyBoy-ico** [comment]
Authorization: Bearer TOKEN1,TOKEN2,TOKEN3 我是按照这个添加了几个token，还有检查传入的token是否有效，请求/token/check接口的话，我是写在请求问题之前嘛

    async def ai_ana_ask(self, params, stream=False):
        model_mapping = {
            1: 'model',
            2: 'spark',
            3: 'kimi'
        }
        model_key = model_mapping.get(params['platform_type'], 'model')
        data = {
            'model': model_key,
            'conversation_id': params['convers_id'],
            'messages': [{
                'role': 'user',
                'content': params['question']
            }],
            'stream': stream
        }
        if params['platform_type'] == 2:
            data['model'] = 'spark'
            authorization = self.spark_token
            url = self.spark_url
        elif params['platform_type'] == 3:
            data['model'] = 'kimi'
            data['use_search'] = True
            authorization = self.kimi_token
            url = self.kimi_url
        else:
            # 默认模型无需再次赋值，已在model_mapping中设定
            authorization = self.qwen_token
            url = self.qwen_url

        headers = {
            'Authorization': authorization,
            'Content-Type': 'application/json'
        }
        # 检测token是否有效或同一个token
            # code....
        
        response = requests.post(url, headers=headers, json=data)
        res = response.json()
        print(res)
        code = res.get('code', None)
        if code is None:
            answer_content = res.get('choices', [])[0].get('message', {}).get('content')
            return Response.success('success', {'id': res.get('id'), 'answer': answer_content})

        return Response.error(res.get('message'))
