### ISSUE TITLE
这个组织好牛逼，请问怎样加入这个组织，这个组织能逆向gemini labs.perplexity openai吗

### ISSUE THREAD

**Issue by leezhuuu** [LLM-Red-Team/qwen-free-api#4]
这个组织好牛逼，请问怎样加入这个组织，这个组织能逆向gemini labs.perplexity openai吗

**Comment by Vinlic** [comment]
@leezhuuu 组织主要是为了评测并公开国内现有LLM应用的风险，暂时还没触及其它模型，可以先加入Free API群，后续组织需要扩展人员时会邀请
![50fa23c932813f00df36813bdd0e222](https://github.com/LLM-Red-Team/qwen-free-api/assets/20235341/35c15904-20fb-4859-a5df-3e205cc0a408)
