### ISSUE TITLE
login_tongyi_ticket这个字段cookies里面没了，是不是阿里更新了

### ISSUE THREAD

**Issue by chenwei39094342** [LLM-Red-Team/qwen-free-api#40]
login_tongyi_ticket这个字段cookies里面没了，是不是阿里更新了

**Comment by CaiJianling** [comment]
应该是的

**Comment by Vinlic** [comment]
我们测试都有，请重新登录查看

**Comment by zhcngh** [comment]
我的也没有了
![image](https://github.com/LLM-Red-Team/qwen-free-api/assets/20473163/d50cbd3b-bb65-427a-8389-8c45df7a5e30)

**Comment by Vinlic** [comment]
通过多个账号验证确认部分账号的login_tongyi_ticket已经开始失效，0.0.20版本已经改为使用`tongyi_sso_ticket`，请升级。
