### ISSUE TITLE
关于多轮会话的问题，关于体验原生多轮会话问题

### ISSUE THREAD

**Issue by dpengchen** [LLM-Red-Team/qwen-free-api#44]
关于多轮会话的问题，关于体验原生多轮会话；

我查看代码之后，发现每次对话之后都会删除这个会话；我想作者可能在考虑的是多个 authority token 会话太多的问题；所以每次询问完了之后就删除对话；

对于单个人的token来说的话，又不能体验到原生的多轮会话

![image](https://github.com/user-attachments/assets/96d1f7c5-aa87-4afb-a6ec-a05a1ee04c7b)

但是wo我觉得奇怪的是为什么 不用 SSE 流的话不会删除？

都同样调用了这个函数

**Comment by Vinlic** [comment]
原生多轮也提供支持，可以参考文档，只是使用原生多轮的时候不会移除会话，因为移除后就无法进行下一轮了
如果用默认的上下轮合并多轮，就会每次都移除，为了避免会话堆积过多

**Comment by stan5215** [comment]
![image](https://github.com/user-attachments/assets/88b7f385-32c4-47ed-ac2e-8bfdca7ddc4d)
我也遇到了这个问题，"stream":true就会出现，"stream":false的时候多轮会话是正常的。

**Comment by dpengchen** [comment]
你可以更改一下他的源代码，在chat.ts中注释掉一行就可以避免这个问题了，但是要自己手动去官网删除记录，或者自己再写一个api

**Comment by dpengchen** [comment]
> ![image](https://private-user-images.githubusercontent.com/51010434/363099127-88b7f385-32c4-47ed-ac2e-8bfdca7ddc4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMDY5MDIsIm5iZiI6MTcyNTAwNjYwMiwicGF0aCI6Ii81MTAxMDQzNC8zNjMwOTkxMjctODhiN2YzODUtMzJjNC00N2VkLWFjMmUtOGJmZGNhN2RkYzRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDA4MzAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkMGU4N2QxYTAyMDg1NmZlY2FhZDRhYmU1YmM3ZDczNzU2MDU5NDJhMGZmMDZlM2E2ZjVmYjg4ZjI4Yjk2NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l2TDIxHAYGfNB4upI9lQ7103YR9f5_mVfJkmygGZqjA) 我也遇到了这个问题，"stream":true就会出现，"stream":false的时候多轮会话是正常的。

你可以更改一下他的源代码，在chat.ts中注释掉一行就可以避免这个问题了，但是要自己手动去官网删除记录，或者自己再写一个api

**Comment by stan5215** [comment]
> > ![image](https://private-user-images.githubusercontent.com/51010434/363099127-88b7f385-32c4-47ed-ac2e-8bfdca7ddc4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMDY5MDIsIm5iZiI6MTcyNTAwNjYwMiwicGF0aCI6Ii81MTAxMDQzNC8zNjMwOTkxMjctODhiN2YzODUtMzJjNC00N2VkLWFjMmUtOGJmZGNhN2RkYzRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDA4MzAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkMGU4N2QxYTAyMDg1NmZlY2FhZDRhYmU1YmM3ZDczNzU2MDU5NDJhMGZmMDZlM2E2ZjVmYjg4ZjI4Yjk2NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l2TDIxHAYGfNB4upI9lQ7103YR9f5_mVfJkmygGZqjA) 我也遇到了这个问题，"stream":true就会出现，"stream":false的时候多轮会话是正常的。
> 
> 你可以更改一下他的源代码，在chat.ts中注释掉一行就可以避免这个问题了，但是要自己手动去官网删除记录，或者自己再写一个api

谢谢，我也很奇怪为什么非流式接口不会删除会话，看来要跑代码才知道了
