### ISSUE TITLE
貌似已经不支持图像识别功能

### ISSUE THREAD

**Issue by lrbmike** [LLM-Red-Team/qwen-free-api#47]
上传了图片以后的回复：
作为一个文本生成模型，我没有视觉能力，所以我不能“看到”任何东西。我只能处理和回应通过文本输入的信息。如果你有任何问题或需要帮助，可以告诉我，我会尽力提供帮助。

**Comment by haige268** [comment]
我也遇到了这个问题，你后来解决了吗？

**Comment by lrbmike** [comment]
> 我也遇到了这个问题，你后来解决了吗？

只能等作者修复更新

**Comment by Vinlic** [comment]
qwen-free-api 0.0.21
已修复，请更新。
