### ISSUE TITLE
文档解读时oss上传失败

### ISSUE THREAD

**Issue by stan5215** [LLM-Red-Team/qwen-free-api#48]
![image](https://github.com/user-attachments/assets/fe2b81c8-3061-4aec-b751-d1dce1848cca)
官网的是：https://broadscope-dialogue-new.oss-cn-beijing.aliyuncs.com/

**Comment by 332123342** [comment]
<img width="1038" alt="企业微信截图_1dc168bf-009b-41bc-8379-d17ee2ae7f42" src="https://github.com/user-attachments/assets/afb536f1-e68e-4611-bd27-88ded7477504">

**Comment by Vinlic** [comment]
qwen-free-api 0.0.21
已修复，请更新。
