### ISSUE TITLE
这里的 refresh_token 如何获取呢？

### ISSUE THREAD

**Issue by ymsha88** [LLM-Red-Team/qwen-free-api#49]
![image](https://github.com/user-attachments/assets/6f814436-b443-4714-b99b-bbe2d9fcbdc5)

**Comment by ymsha88** [comment]
对话补全
对话补全接口，与openai的 [chat-completions-api](https://platform.openai.com/docs/guides/text-generation/chat-completions-api) 兼容。

POST /v1/chat/completions

header 需要设置 Authorization 头部：

Authorization: Bearer [tongyi_sso_ticket/login_aliyunid_ticket]
请求数据：

{
    // 模型名称随意填写
    "model": "qwen",
    // 目前多轮对话基于消息合并实现，某些场景可能导致能力下降且受单轮最大token数限制
    // 如果您想获得原生的多轮对话体验，可以传入上一轮消息获得的id，来接续上下文
    // "conversation_id": "bc9ef150d0e44794ab624df958292300-40811965812e4782bb87f1a9e4e2b2cd",
    "messages": [
        {
            "role": "user",
            "content": "你是谁？"
        }
    ],
    // 如果使用SSE流请设置为true，默认false
    "stream": false
}

[tongyi_sso_ticket/login_aliyunid_ticket] 这个有获取方式，可以用
但是 以下的 [refresh_token[不知道如何获取
图像解析
提供一个可访问的图像URL或者BASE64_URL进行解析。

此格式兼容 [gpt-4-vision-preview](https://platform.openai.com/docs/guides/vision) API格式，您也可以用这个格式传送文档进行解析。

POST /v1/chat/completions

header 需要设置 Authorization 头部：

Authorization: Bearer **[refresh_token]**
请求数据：

{
    "model": "qwen",
    "messages": [
        {
            "role": "user",
            "content": [
                {
                    "type": "file",
                    "file_url": {
                        "url": "https://img.alicdn.com/imgextra/i1/O1CN01CC9kic1ig1r4sAY5d_!!6000000004441-2-tps-880-210.png"
                    }
                },
                {
                    "type": "text",
                    "text": "图像描述了什么？"
                }
            ]
        }
    ]
}

**Comment by ymsha88** [comment]
如果用 [tongyi_sso_ticket/login_aliyunid_ticket] ，返回的结果是
{"code":-1000,"message":"Request failed with status code 403","data":null]

**Comment by Vinlic** [comment]
qwen-free-api 0.0.21
已修复，请更新。
