### ISSUE TITLE
【bug】free-qwen视觉模型失效

### ISSUE THREAD

**Issue by haige268** [LLM-Red-Team/qwen-free-api#50]
![屏幕截图_22-9-2024_184054_10 9 50 108](https://github.com/user-attachments/assets/18dc701f-f051-4d0c-bb29-90ed1dce5189)
![11111](https://github.com/user-attachments/assets/b0723532-33b0-4144-80a4-8faa00dbb185)
fastgpt调用的时候，文本对话没问题，但是视觉模型进行识图就报这个错。也试了free-kimi是可以正常识图的。请核实这个问题。谢谢！

**Comment by Vinlic** [comment]
qwen-free-api 0.0.21
已修复，请更新。
