### ISSUE TITLE
是否方便完善一下配置教程？

### ISSUE THREAD

**Issue by kknd222** [LLM-Red-Team/qwen-free-api#8]
比如restful工具的演示，各类前端的配置演示？

**Comment by Vinlic** [comment]
@kknd222 暂时没有精力做教程部分，目前有部分博主在B站发布了使用教程，可以作为参考，各类前端客户端配置都很简单。
https://www.bilibili.com/video/BV12m421n7w4
https://www.bilibili.com/video/BV1Rm421J7jf
https://www.bilibili.com/video/BV1dr42187VJ
https://www.bilibili.com/video/BV1XC411V7uh
